# Generated by Django 5.2.1 on 2025-05-31 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=256)),
                ('code', models.CharField(max_length=256, unique=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=256, unique=True)),
                ('is_official', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='defaultdb.user')),
            ],
            options={
                'db_table': 'tag',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=256)),
                ('article_path', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='defaultdb.user')),
            ],
            options={
                'db_table': 'article',
            },
        ),
        migrations.CreateModel(
            name='UserTagRelation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='defaultdb.tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='defaultdb.user')),
            ],
            options={
                'db_table': 'user_tag_relation',
            },
        ),
        migrations.CreateModel(
            name='ArticleTagRelation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='defaultdb.article')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='defaultdb.tag')),
            ],
            options={
                'db_table': 'article_tag_relation',
                'constraints': [models.UniqueConstraint(fields=('article', 'tag'), name='article_and_tag_uniq')],
            },
        ),
        migrations.AddConstraint(
            model_name='article',
            constraint=models.UniqueConstraint(fields=('user', 'title'), name='article_title_and_user_uniq'),
        ),
        migrations.AddConstraint(
            model_name='usertagrelation',
            constraint=models.UniqueConstraint(fields=('user', 'tag'), name='user_and_tag_uniq'),
        ),
    ]
