# Generated by Django 5.2.4 on 2025-07-06 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defaultdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CycleRelationA',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'cycle_relation_a',
            },
        ),
        migrations.CreateModel(
            name='CycleRelationB',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cycle_relation_a', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='defaultdb.cyclerelationa')),
            ],
            options={
                'db_table': 'cycle_relation_b',
            },
        ),
        migrations.AddField(
            model_name='cyclerelationa',
            name='cycle_relation_b',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='defaultdb.cyclerelationb'),
        ),
    ]
