AWSTemplateFormatVersion: "2010-09-09"
Description: cleanup db codebuild resources

Parameters:
  GitHubSourceRepository:
    Type: String
    Description: GitHub Repository Url.
  DBName:
    Type: String
    Description: Default DB Name
  DBMasterId:
    Type: String
    Description: DB Master ID
  DBMasterPassword:
    Type: String
    Description: DB Master Password

Resources:
  ServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Join [ "-", [ cleanup, db, codeBuild, serviceRole] ]
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: "/"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/CloudWatchFullAccess"
        - "arn:aws:iam::aws:policy/AWSCodeBuildDeveloperAccess"
        - "arn:aws:iam::aws:policy/AmazonRDSFullAccess"
        - "arn:aws:iam::aws:policy/AmazonEC2FullAccess"
        - "arn:aws:iam::aws:policy/SecretsManagerReadWrite"
        - "arn:aws:iam::aws:policy/AmazonEventBridgeFullAccess"

  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Join [ "-", [ cleanup, db, CodeBuild ] ]
      Source:
        Location: !Ref GitHubSourceRepository
        Type: GITHUB
        GitCloneDepth: 1
        BuildSpec: "buildspec.yml"
      SourceVersion: main
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:7.0
        EnvironmentVariables:
          - Name: MYSQL_HOST
            Value: !ImportValue MyRDSHostEndpoint
          - Name: MYSQL_DATABASE
            Value: !Ref DBName
          - Name: MYSQL_USER
            Value: !Ref DBMasterId
          - Name: MYSQL_PASSWORD
            Value: !Ref DBMasterPassword
      ServiceRole: !GetAtt ServiceRole.Arn
      Artifacts:
        Type: NO_ARTIFACTS
      VpcConfig:
        SecurityGroupIds:
          - !ImportValue CommonCodeBuildSGId
        Subnets:
          - !ImportValue PrivateSubnetId
        VpcId: !ImportValue VpcId

  EventBridgeInvokeRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Join [ "-", [ cleanup, db, event, invoke, role ] ]
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - events.amazonaws.com
            Action: "sts:AssumeRole"
      Path: "/"
      Policies:
        - PolicyName: "AllowInvokeCodeBuild"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - codebuild:StartBuild
                Resource: !GetAtt CodeBuildProject.Arn

  CodeBuildTriggerRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Join [ "-", [ cleanup, db, codeBuild, trigger, rule ] ]
      ScheduleExpression: "cron(0 15 * * ? *)"
      State: ENABLED
      Targets:
        - Arn: !GetAtt CodeBuildProject.Arn
          Id: "CodeBuildProjectTarget"
          RoleArn: !GetAtt EventBridgeInvokeRole.Arn
